"""Pack piko's MetaConfig name list into the Java class the extension carries.

Reads one of crimera/piko's docs/mappings/<version>.json files (https://github.com/crimera/piko,
GPL-3.0), a JSON array of "configId:config_name:index:param_name:index:param_name..." strings, and
writes

  extensions/instagram/src/main/java/app/hushgram/extension/instagram/misc/FlagNameData.java

Usage: py -3.13 -I scripts/gen-flag-names.py <mapping.json> [--check]

The list shipped now is docs/mappings/447.0.0.55.81.json at piko commit
ea752648f5688a50a96df21430020e98bf9ece00 (SHA-256 3bc238c717001737c925c2f31d4fae42644943e47d165490c1836f40dc2da441).
--check rebuilds the class from the file and fails if the checked-in one differs.

Packing. Names are split at "_" into words, and each distinct word becomes a number in a table
(most used first, so the common ones are short). The text is: the word count, the words one per
line, then one line per config (sorted by number) of ":" separated fields: the number as a
difference from the previous config, the config name as dot-joined hexadecimal word numbers, then
for each parameter its index as a difference from the previous one and its name. That text is
deflated (zlib) and written as base64 in chunks under the 64 KB limit on a Java string constant,
so the extension's dex holds about 450 KB for the 41,075 names instead of the 1.6 MB mapping.
The reader is FlagNames.shipped, and FlagNamesTest decodes the class back to the same names.
"""
import base64
import collections
import hashlib
import json
import sys
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "extensions/instagram/src/main/java/app/hushgram/extension/instagram/misc/FlagNameData.java"
SOURCE = "docs/mappings/447.0.0.55.81.json"
COMMIT = "ea752648f5688a50a96df21430020e98bf9ece00"
CHUNK = 60000


def read(path):
    raw = Path(path).read_bytes()
    entries = json.loads(raw.decode("utf-8"))
    rows = {}
    for entry in entries:
        parts = entry.split(":")
        if len(parts) < 2 or len(parts) % 2:
            raise SystemExit(f"unreadable entry {entry[:60]!r}")
        config = int(parts[0])
        if config in rows:
            raise SystemExit(f"config {config} repeats")
        params = {}
        for at in range(2, len(parts), 2):
            index = int(parts[at])
            if index in params:
                raise SystemExit(f"config {config} repeats parameter {index}")
            params[index] = parts[at + 1]
        names = [parts[1]] + list(params.values())
        for name in names:
            if not name or any(not 32 < ord(c) < 127 for c in name):
                raise SystemExit(f"config {config} has a name that isn't plain ASCII: {name!r}")
        rows[config] = (parts[1], sorted(params.items()))
    return raw, rows


def pack(rows):
    words = collections.Counter()
    for config in rows.values():
        for name in [config[0]] + [n for _, n in config[1]]:
            words.update(name.split("_"))
    vocab = [w for w, _ in sorted(words.items(), key=lambda item: (-item[1], item[0]))]
    number = {w: i for i, w in enumerate(vocab)}

    def encode(name):
        return ".".join(format(number[w], "x") for w in name.split("_"))

    lines = [str(len(vocab))] + vocab
    previous = 0
    parameters = 0
    for config in sorted(rows):
        name, params = rows[config]
        fields = [str(config - previous), encode(name)]
        previous = config
        last = 0
        for index, pname in params:
            fields += [str(index - last), encode(pname)]
            last = index
            parameters += 1
        lines.append(":".join(fields))
    return zlib.compress("\n".join(lines).encode("ascii"), 9), parameters


def java(raw, rows):
    packed, parameters = pack(rows)
    text = base64.b64encode(packed).decode("ascii")
    chunks = [text[i:i + CHUNK] for i in range(0, len(text), CHUNK)]
    out = [
        "/*",
        f" * Generated by scripts/gen-flag-names.py from {SOURCE} in crimera/piko",
        " * https://github.com/crimera/piko (GPL-3.0), commit " + COMMIT + ".",
        " * Modified for HushGram, 2026. https://github.com/SysAdminDoc/HushGram",
        " */",
        "package app.hushgram.extension.instagram.misc;",
        "",
        "/**",
        " * Instagram's MetaConfig names as piko's mapping for Instagram 447 lists them, packed small: see",
        " * scripts/gen-flag-names.py for the format, and {@link FlagNames} for the reader. Generated, so",
        " * edit the script and not this file.",
        " */",
        "final class FlagNameData {",
        "    private FlagNameData() {",
        "    }",
        "",
        f"    static final String SOURCE = \"piko {SOURCE}\";",
        f"    static final String COMMIT = \"{COMMIT}\";",
        f"    static final String SHA256 = \"{hashlib.sha256(raw).hexdigest()}\";",
        f"    static final int CONFIGS = {len(rows)};",
        f"    static final int PARAMETERS = {parameters};",
        "",
        "    /** The packed list as base64, in pieces that each fit a Java string constant. */",
        "    static final String[] PACKED = {",
    ]
    out += [f"        \"{chunk}\"," for chunk in chunks]
    out += ["    };", "}", ""]
    return "\n".join(out)


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if len(args) != 1:
        raise SystemExit(__doc__)
    raw, rows = read(args[0])
    source = java(raw, rows)
    if "--check" in sys.argv:
        if TARGET.read_text(encoding="ascii") != source:
            raise SystemExit(f"{TARGET} is out of date; run scripts/gen-flag-names.py")
        print("FlagNameData.java is current")
        return
    TARGET.write_text(source, encoding="ascii", newline="\n")
    print(f"wrote {TARGET.relative_to(ROOT)}: {len(rows)} configs, {len(source)} bytes")


if __name__ == "__main__":
    main()
